config/routes.rb
Rails.application.routes.draw do
  # Directs devise to use the registration controller
  devise_for :users, :controllers => { registrations: "registrations" }
  resources :posts
  root "pages#index"
  get "posts/"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  # Unless the user is logged in, they can't view anything except the index and show variables
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    # Orders than based on the "created_at" variable in a descending order
    @posts = Post.all.order ("created_at DESC")
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  # Checks if the user is signed in
  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  #   Triggers when the player tries to update account settings
  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smoke Market</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href=”https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
    <%# When the user does something, this notifies them if the action is successful %>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <%# If user encounters an error, this will notify them of the issue %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= render "pages/header"%>
    <%= yield %>
  </body>
</html>

app/views/pages/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Smoke</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="posts/" href="/pages/community">Community</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/games">Store</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/pages/profile">Profile</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/edit">Edit Profile</a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_up">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_in">Sign In</a>
          </li>
        <% end %>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success search" type="submit" style="visibility: hidden">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/pages/index.html.erb
Welcome to Smoke

app/views/posts/_feed.html.erb
<div class="box">
  <article class="media box">
    <figure class="media-left">
      <% @posts.each do | post | %>
        <div class="card">
          <div class="card-body">
            <p class="image is-64x64">
              <img src="https://bulma.io/images/placeholders/64x64.png" style="border-radius: 50%">
            </p>
<<<<<<< HEAD
            <h5 class="card-title"><%= post.user.name%></h5>
            <h6 class="card-subtitle mb-2 text-muted">@<%= post.user.username %></h6>
            <p class="card-text"><%= post.content %></p>
=======
            <h5 class="card-title">USER NAME HERE</h5>
            <h6 class="card-subtitle mb-2 text-muted">@USERNAME HERE</h6>
            <p class="card-text"><%= post.content%></p>
            <%= link_to 'Edit', edit_post_path(post), class: "btn btn-dark btn-secondary btn-sm" %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post??' }, 
            class: "btn btn-dark btn-secondary btn-sm"  %>
>>>>>>> parent of 4e881992 (Community Complete)
          </div>
        </div>
        <% if user_signed_in? && current_user.id == post.user_id %>
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-dark btn-secondary btn-sm" %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post??' }, 
            class: "btn btn-dark btn-secondary btn-sm"  %>
            </div>
          </nav>
        <% end %>
      <%end%>
    </figure>
  </article>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: @post) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <p id="notice"><%= notice %></p>
      <h1>Community</h1>
      <table>
        <% if user_signed_in? %>
          <div class="card-body">
            <p class="image is-64x64">
              <img src="https://bulma.io/images/placeholders/64x64.png" style="border-radius: 50%">
            </p>
            <h5 class="card-title"><%= current_user.name%></h5>
            <h6 class="card-subtitle mb-2 text-muted">@<%= current_user.username %></h6>
            <%= render "posts/form"%>
          </div>
        <% end%>
        <br>
        <%= render "posts/feed"%>
      </table>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>